version: '3.9'

services:
  api:
    container_name: api-with-drizzle
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - api-with-drizzle-network
    volumes:
      - .:/app

  postgres:
    container_name: postgres-api-with-drizzle
    image: postgres:14-alpine
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
     - 5432:5432
    networks:
      - api-with-drizzle-network
    volumes:
      - data:/var/lib/postgresql/data

networks:
  api-with-drizzle-network:

volumes:
  data: