version: '3.9'

services:
  postgres:
    container_name: postgres-api-with-drizzle
    image: postgres:14-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - docker.env